YeZiFang.Admin/Controllers/ProjectController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using YeZiFang.Service;
using YeZiFang.DataContract.Request;
using YeZiFang.DataContract.Response;
using Shitou.Framework.ORM;
using YeZiFang.Model;
using YeZiFang.Application.Models;
using Microsoft.AspNetCore.Authorization;
using YeZiFang.Common;
using YeZiFang.Model.Common;
using YeZiFang.DataContract.Base;

namespace YeZiFang.Admin.Controllers
{
    /// <summary>
    /// 楼盘模块
    /// </summary>
    [Authorize]
    public class ProjectController : BaseController
    {
        public IProjectService ProjectService { get; set; }
        public ProjectController(IProjectService projectService)
        {
            ProjectService = projectService;
        }

        #region 楼盘管理
        /// <summary>
        /// 楼盘列表
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        public ActionResult ProjectList(GetProjectListRequest request)
        {
            //request.CityId = CityId;
            Pager<GetProjectListResponse> list = ProjectService.GetProjectList(request);
            return View(list);
        }
        /// <summary>
        /// 楼盘添加
        /// </summary>
        /// <returns></returns>
        public ActionResult ProjectAdd()
        {
            ViewData["AreaData"] = new SelectList(ProjectService.GetList<AreaInfo>("CityId", CityId), "ID", "AreaName");
            return View(new ProjectInfo());
        }
        /// <summary>
        /// 楼盘添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ProjectAdd(ProjectInfo info)
        {
            CityInfo cityInfo = ProjectService.GetModel<CityInfo>("ID", CityId);
            info.ID = StringUtils.GenerateUniqueID();
            info.CreateBy = LoginUserInfo.ID;
            info.CreateTime = DateTime.Now;
            info.ProvinceId = cityInfo.ID;
            if (ProjectService.Insert(info))
            {
                Result.IsOk = true;
                Result.Msg = "添加成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "添加失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 楼盘添加
        /// </summary>
        /// <returns></returns>
        public ActionResult ProjectEdit(string id)
        {
            ProjectInfo info = ProjectService.GetModel<ProjectInfo>("ID", id);
            List<DicDataInfo> dicData = ProjectService.GetList<DicDataInfo>();
            ViewData["PurposeData"] = new SelectList(dicData.Where(a => a.ParentId == Consts.Purpose).ToList(), "Value", "Name");
            ViewData["FitmentData"] = new SelectList(dicData.Where(a => a.ParentId == Consts.Fitment).ToList(), "Value", "Name");
            ViewData["ProvinceData"] = new SelectList(ProjectService.GetList<ProvinceInfo>(), "ID", "ProvinceName");
            ViewData["CityData"] = new SelectList(ProjectService.GetList<CityInfo>("ProvinceId", info.ProvinceId), "ID", "CityName");
            ViewData["AreaData"] = new SelectList(ProjectService.GetList<AreaInfo>("CityId", info.CityId), "ID", "AreaName");
            
            return View(info);
        }
        /// <summary>
        /// 楼盘添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ProjectEdit(ProjectInfo info)
        {
            if (ProjectService.Update(info))
            {
                Result.IsOk = true;
                Result.Msg = "更新成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "更新失败";
            }
            return Json(Result);
        }
        #endregion

    }
}

YeZiFang.Admin/Views/Project/ProjectAdd.cshtml
@model ProjectInfo

<body>
    <form id="ProjectAdd" class="layui-form layui-form-pane"
          asp-controller="Project" asp-action="ProjectAdd"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("ProjectForm")
    </form>
</body>

YeZiFang.Admin/Views/Project/ProjectEdit.cshtml
@model ProjectInfo

<body>
    <form id="ProjectEdit" class="layui-form layui-form-pane"
          asp-controller="Project" asp-action="ProjectEdit"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("ProjectForm")
    </form>
</body>

YeZiFang.Admin/Views/Project/ProjectForm.cshtml
@model ProjectInfo
<table class="post-form">
    <tr>
        <th style="width: 150px;">楼盘名称：</th>
        <td>
            <input id="ProjectName" name="ProjectName" lay-verify="required" lay-msg="楼盘名称不能为空" class="layui-input" type="text" value="@Model.ProjectName">
        </td>
        <th>楼盘别名：</th>
        <td>
            <input id="ProjectOtherName" name="ProjectOtherName" class="layui-input" type="text" value="@Model.ProjectOtherName">
            @Html.HiddenFor(model => model.CreateBy)
            @Html.HiddenFor(model => model.CreateTime)
            @Html.HiddenFor(model => model.UpdateBy)
            @Html.HiddenFor(model => model.UpdateTime)
        </td>
    </tr>
    <tr>
        <th>用途：</th>
        <td>
            @Html.DropDownList("Purpose", ViewData["PurposeData"] as SelectList, "-请选择-", new { @class = "layui-input" })
        </td>
        <th>装修：</th>
        <td>
            @Html.DropDownList("Fitment", ViewData["FitmentData"] as SelectList, "-请选择-", new { @class = "layui-input" })
        </td>
    </tr>
    <tr>
        <th>开发商：</th>
        <td>
            <input id="ProjectDeveloper" name="ProjectDeveloper" class="layui-input" type="text" value="@Model.Developer">
        </td>
        <th>楼盘均价：</th>
        <td>
            <input id="AvgPrice" name="AvgPrice" class="layui-input" lay-verify="number" type="text" value="@Model.AvgPrice">
        </td>
    </tr>
    <tr>
        <th>行政区：</th>
        <td>
            @Html.DropDownList("ProvinceId", ViewData["ProvinceData"] as SelectList, "-请选择-", new { @class = "layui-input" })
            @Html.DropDownList("CityId", ViewData["CityData"] as SelectList, "-请选择-", new { @class = "layui-input" })
            @Html.DropDownList("AreaId", ViewData["AreaData"] as SelectList, "-请选择-", new { @class = "layui-input" })
        </td>
        <th>特色：</th>
        <td>
            <input id="Feature" name="Feature" class="layui-input" type="text" value="@Model.Feature">
        </td>
    </tr>
    <tr>
        <th>地址：</th>
        <td colspan="3">
            <input id="Address" name="Address" class="layui-input" type="text" value="@Model.Address">
        </td>
    </tr>
    <tr>
        <th>经度：</th>
        <td>
            <input id="Longitude" name="Longitude" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.Longitude">
        </td>
        <th>纬度：</th>
        <td>
            <input id="Latitude" name="Latitude" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.Latitude">
        </td>
    </tr>
    <tr>
        <th>使用年限：</th>
        <td>
            <input id="UsefulLife" name="UsefulLife" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.UsefulLife">
        </td>
        <th>总套数：</th>
        <td>
            <input id="TotalHouseCount" name="TotalHouseCount" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.TotalHouseCount">
        </td>
    </tr>
    <tr>
        <th>占地面积：</th>
        <td>
            <input id="LandArea" name="LandArea" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.LandArea">
        </td>
        <th>建筑面积：</th>
        <td>
            <input id="BuildingArea" name="BuildingArea" class="layui-input" lay-verify="number" lay-msg="输入有误" type="text" value="@Model.BuildingArea">
        </td>
    </tr>
    <tr>
        <th></th>
        <td>
            <button id="post_btn" type="submit" class="layui-btn" lay-submit="" lay-filter="post">保 存</button>
            <a href="javascript:void(0)" onclick="parent.CloseWindow();" class="layui-btn layui-btn-normal">返回列表</a>
        </td>
    </tr>
</table>
<script>
    layui.use(['form', 'layer'], function () {
        var form = layui.form,
        layer = layui.layer;
        //自定义验证规则
        form.verify({
            confirmPassword: function (value) {
                if (value != $('#Password').val()) {
                    return '两次输入密码不一致！';
                }
            }
        });
        //监听提交
        form.on('submit(post)', function (data) {
            console.log(JSON.stringify(data.field));
            return true;
        });
    });
</script>

YeZiFang.Admin/Views/Project/ProjectList.cshtml
@model Pager<GetProjectListResponse>
@{
    ViewBag.Title = "楼盘列表";
}

<div class="container">
    @using (Html.BeginForm("ProjectList", "Project", FormMethod.Get, new { @class = "layui-form search-form layui-elem-quote", @id = "searchForm" }))
    {
        <table>
            <tr>
                <th>名称：</th>
                <td>
                    <input id="ProjectName" name="ProjectName" class="layui-input" type="text" value="">
                </td>
                <td>
                    <input type="submit" class="layui-btn layui-btn-sm" value="查 询" />
                </td>
            </tr>
        </table>
    }
        <div style="padding:0px 10px;">
            <a class="layui-btn layui-btn-sm layui-btn-normal" href="javascript:void(0);" onclick="AddOrEdit()">
                <i class="layui-icon layui-icon-tianjia2"></i>添加楼盘</a>
        </div>
    <table class="layui-table" id="list">
        <thead>
            <tr>
                <th style="width:45px; text-align:center;">#</th>
                <th>楼盘名称</th>
                <th>楼盘均价(元/㎡)</th>
                <th>楼盘地址</th>
                <th>开发商</th>
                <th style="width:120px;">操作</th>
            </tr>
        </thead>
        <tbody>
            @{ int index = 1;}
            @foreach (var item in Model)
            {
            <tr>
                <td style="width:45px; text-align:center;">@(index++)</td>
                <td>@item.ProjectName</td>
                <td>@(item.AvgPrice <= 0 ? "待定" : item.AvgPrice.ToString("0"))</td>
                <td>@item.Address</td>
                <td>@item.Developer</td>
                <td>
                    <a class="layui-btn layui-btn-normal layui-btn-xs" href="javascript:void(0)" onclick="AddOrEdit('@item.ID')"><i class="layui-icon layui-icon-bianji"></i>编辑</a>
                    <a class="layui-btn layui-btn-danger layui-btn-xs" onclick="javascript:Delete('/System/ProjectDelete/@item.ID');"><i class="layui-icon layui-icon-delete"></i>删除</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    @await Html.PartialAsync("_Pager", Model)
</div>
<script>
    function AddOrEdit(id) {
        if (id == undefined) {
            ShowMaxWindow('===添加楼盘信息===', '/Project/ProjectAdd');
        }
        else {
            ShowMaxWindow('===编辑楼盘信息===', '/Project/ProjectEdit/' + id);
        }
    }
</script>