YeZiFang.Admin/Controllers/SystemController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using YeZiFang.Service;
using YeZiFang.DataContract.Request;
using YeZiFang.DataContract.Response;
using Shitou.Framework.ORM;
using YeZiFang.Model;
using YeZiFang.Application.Models;
using Microsoft.AspNetCore.Authorization;
using YeZiFang.Common;

namespace YeZiFang.Admin.Controllers
{
    /// <summary>
    /// 用户模块
    /// </summary>
    [Authorize]
    public class SystemController : BaseController
    {
        public ISystemService SystemService { get; set; }
        public SystemController(ISystemService systemService)
        {
            SystemService = systemService;
        }

        #region 用户管理
        /// <summary>
        /// 用户列表
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        public ActionResult UserList(GetUserListRequest request)
        {
            Pager<GetUserListResponse> list = SystemService.GetUserList(request);
            return View(list);
        }
        /// <summary>
        /// 用户添加
        /// </summary>
        /// <returns></returns>
        public ActionResult UserAdd()
        {
            ViewData["Roles"] = new SelectList(SystemService.GetList<RoleInfo>(), "ID", "RoleName");
            return View(new UserInfo());
        }
        /// <summary>
        /// 用户添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UserAdd(UserInfo info, IFormCollection form)
        {
            info.IsAdmin = form["IsAdmin"].ToString().ToLower() == "on" ? true : false;

            info.ID = StringUtils.GenerateUniqueID();
            info.Password = RSADEncrypt.Encrypt(info.Password);
            info.CreateBy = LoginUserInfo.ID;
            info.CreateTime = DateTime.Now;

            if (SystemService.Insert(info))
            {
                Result.IsOk = true;
                Result.Msg = "添加成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "添加失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 用户添加
        /// </summary>
        /// <returns></returns>
        public ActionResult UserEdit(string id)
        {
            ViewData["Roles"] = new SelectList(SystemService.GetList<RoleInfo>(), "ID", "RoleName");
            UserInfo info = SystemService.GetModel<UserInfo>("ID", id);
            return View(info);
        }
        /// <summary>
        /// 用户添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UserEdit(UserInfo info, IFormCollection form)
        {
            info.IsAdmin = form["IsAdmin"].ToString().ToLower() == "on" ? true : false;
            if (SystemService.Update(info))
            {
                Result.IsOk = true;
                Result.Msg = "更新成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "更新失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public ActionResult UserDelete(string id)
        {
            if (SystemService.Delete<UserInfo>("ID", id))
            {
                Result.IsOk = true;
                Result.Msg = "删除成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "删除失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 用户修改密码
        /// </summary>
        /// <returns></returns>
        public ActionResult UserPwd(string id)
        {
            UserInfo info = SystemService.GetModel<UserInfo>("ID", id);
            return View(info ?? new UserInfo());
        }
        /// <summary>
        /// 用户修改密码
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UserPwd(UserInfo info)
        {
            UserInfo user = SystemService.GetModel<UserInfo>("ID", info.ID);
            user.Password= RSADEncrypt.Encrypt(info.Password);
            if (SystemService.Update<UserInfo>(user))
            {
                Result.IsOk = true;
                Result.Msg = "修改成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "修改失败";
            }
            return Json(Result);
        }
        #endregion

        #region 角色管理
        /// <summary>
        /// 角色列表
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        public ActionResult RoleList(GetRoleListRequest request)
        {
            Pager<GetRoleListResponse> list = SystemService.GetRoleList(request);
            return View(list);
        }
        /// <summary>
        /// 角色添加
        /// </summary>
        /// <returns></returns>
        public ActionResult RoleAdd()
        {
            RoleInfo info = new RoleInfo();
            //获取所有权限
            List<AuthInfo> allPermission = SystemService.GetList<AuthInfo>();
            //获取权限
            var ztree = from p in allPermission
                        select new ZTreeData
                        {
                            id = p.ID,
                            pId = p.ParentID,
                            name = p.AuthName,
                            value = p.ID,
                            Checked = false
                        };
            //序列化为ztree所需要的json串
            ViewBag.PermissionList = JsonConvert.SerializeObject(ztree);
            //构造隐藏域的值
            ViewBag.PermissionIDs = "";
            return View(info ?? new RoleInfo());
        }
        /// <summary>
        /// 角色添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RoleAdd(RoleInfo info, IFormCollection form)
        {
            info.ID = StringUtils.GenerateUniqueID();
            info.CreateBy = LoginUserInfo.ID;
            info.CreateTime = DateTime.Now;
            if (SystemService.Insert(info))
            {
                string permissionIDs = form["PermissionIDs"];
                SystemService.Insert(GetRolePermissionList(info.ID, permissionIDs));
                Result.IsOk = true;
                Result.Msg = "添加成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "添加失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 角色添加
        /// </summary>
        /// <returns></returns>
        public ActionResult RoleEdit(string id)
        {
            RoleInfo info = SystemService.GetModel<RoleInfo>("ID", id);
            //获取所有权限
            List<AuthInfo> allPermission = SystemService.GetList<AuthInfo>();
            //获取角色对应的权限
            var rolePermission = SystemService.GetList<RoleAuth>("RoleID", id);
            var ztree = from p in allPermission
                        select new ZTreeData
                        {
                            id = p.ID,
                            pId = p.ParentID,
                            name = p.AuthName,
                            value = p.ID,
                            Checked = rolePermission.Exists(a => a.AuthID == p.ID)
                        };
            //序列化为ztree所需要的json串
            ViewBag.PermissionList = JsonConvert.SerializeObject(ztree);
            //构造隐藏域的值
            ViewBag.PermissionIDs = GetRolePermissionIDs(rolePermission);
            return View(info ?? new RoleInfo());
        }
        /// <summary>
        /// 角色添加
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RoleEdit(RoleInfo info, IFormCollection form)
        {
            if (SystemService.Update(info))
            {
                string permissionIDs = form["PermissionIDs"];
                SystemService.Delete<RoleAuth>("RoleID", info.ID);
                SystemService.Insert(GetRolePermissionList(info.ID, permissionIDs));
                Result.IsOk = true;
                Result.Msg = "更新成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "更新失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public ActionResult RoleDelete(string id)
        {
            if (SystemService.Delete<RoleInfo>("ID", id))
            {
                Result.IsOk = true;
                Result.Msg = "删除成功";
            }
            else
            {
                Result.IsOk = false;
                Result.Msg = "删除失败";
            }
            return Json(Result);
        }
        /// <summary>
        /// 获取角色权限List
        /// </summary>
        /// <returns></returns>
        public List<RoleAuth> GetRolePermissionList(string roleID, string permissionIDs)
        {
            List<RoleAuth> list = new List<RoleAuth>();
            foreach (string id in permissionIDs.Split(",".ToArray()))
            {
                if (string.IsNullOrEmpty(id))
                    continue;
                list.Add(new RoleAuth { RoleID = roleID, AuthID = id });
            }
            return list;
        }
        /// <summary>
        /// 构造角色权限ID集
        /// </summary>
        /// <returns></returns>
        public string GetRolePermissionIDs(List<RoleAuth> list)
        {
            string permissinIDs = "";

YeZiFang.Admin/Views/System/AuthAdd.cshtml
@model AuthInfo

<body>
    <form id="UserAdd" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="AuthAdd"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
            @await Html.PartialAsync("AuthForm")
    </form>
</body>

YeZiFang.Admin/Views/System/AuthEdit.cshtml
@model AuthInfo

<body>
    <form id="UserEdit" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="UserEdit"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
            @await Html.PartialAsync("AuthForm")
    </form>
</body>

YeZiFang.Admin/Views/System/AuthForm.cshtml
@model AuthInfo
@{
    Layout = null;
}
<table class="post-form">
    <tr>
        <th style="width: 150px;">父节点：</th>
        <td style="width: 350px;">
            @Html.DropDownList("ParentID", ViewData["AuthList"] as SelectList, "-根节点-")
        </td>
    </tr>
    <tr>
        <th>类别：</th>
        <td>
            @Html.DropDownList("AuthType", ViewData["AuthTypeList"] as SelectList)
        </td>
    </tr>
    <tr>
        <th>权限名称：</th>
        <td>
            <input id="AuthName" name="AuthName" lay-verify="required" lay-msg="权限名不能为空" class="layui-input" type="text" value="@Model.AuthName">
        </td>
    </tr>
    <tr>
        <th>权限编码：</th>
        <td>
            <input id="AuthCode" name="AuthCode" lay-verify="required" lay-msg="权限编码不能为空" class="layui-input" type="text" value="@Model.AuthCode">
        </td>
    </tr>
    <tr>
        <th>URI：</th>
        <td>

            @Html.TextBox("Url", Model.Url, new { @class = "layui-input" })
        </td>
    </tr>
    <tr>
        <th>排序号：</th>
        <td>
            @Html.TextBox("Sort", Model.Sort, new { @class = "layui-input" })
        </td>
    </tr>
    <tr>
        <th></th>
        <td>
            <button id="post_btn" type="submit" class="layui-btn" lay-submit="" lay-filter="post">保 存</button>
            <a href="javascript:void(0)" onclick="parent.CloseWindow();" class="layui-btn layui-btn-normal">返回列表</a>
        </td>
    </tr>
</table>

YeZiFang.Admin/Views/System/AuthList.cshtml
@model List<AuthInfo>
@{
    ViewBag.Title = "权限列表";
}
<script>
    function GetType(t) {
        if (t == 1) {
            document.write('模块');
        }
        if (t == 2)
            document.write('页面');
        if (t == 3)
            document.write('操作');
    }
</script>

<div class="container">
    <div style="padding:0px 10px;">
        <a class="layui-btn layui-btn-sm layui-btn-normal" href="javascript:void(0);" onclick="AddOrEdit()">
            <i class="layui-icon layui-icon-tianjia2"></i>添加权限
        </a>
    </div>
    <table class="layui-table" id="list">
        <thead>
            <tr>
                <th style="width:45px; text-align:center;">#</th>
                <th>权限ID</th>
                <th>权限名</th>
                <th>权限编码</th>
                <th>类型</th>
                <th>Url地址</th>
                <th>排序号</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @{ int index = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:45px; text-align:center;">@(index++)</td>
                    <td>@item.ID</td>
                    <td>@Html.Raw(item.AuthName)</td>
                    <td>@item.AuthCode</td>
                    <td>
                        <script>GetType(@item.AuthType)</script>
                    </td>
                    <td>@item.Url</td>
                    <td>@item.Sort</td>
                    <td>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" onclick="AddOrEdit('@item.ID')"><i class="layui-icon layui-icon-bianji"></i>编辑</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" onclick="javascript:Delete('/System/AuthDelete/@item.ID');"><i class="layui-icon layui-icon-delete"></i>删除</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    function AddOrEdit(id) {
        if (id == undefined) {
            ShowWindow('===添加权限信息===', '/System/AuthAdd', 600, 400);
        }
        else {
            ShowWindow('===编辑权限信息===', '/System/AuthEdit/' + id, 600, 400);
        }
    }
</script>

YeZiFang.Admin/Views/System/LoginOut.cshtml
@{
    ViewBag.Title = "登录退出页面";
}

YeZiFang.Admin/Views/System/RoleAdd.cshtml
@model RoleInfo
<body>
    
    <form id="RoleAdd" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="RoleAdd"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("RoleForm")
    </form>
</body>

YeZiFang.Admin/Views/System/RoleEdit.cshtml
@model RoleInfo
<body>
    
    <form id="RoleEdit" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="RoleEdit"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("RoleForm")
    </form>
</body>

YeZiFang.Admin/Views/System/RoleForm.cshtml
@model RoleInfo
<link href="/lib/zTree_v3/css/zTreeStyle/zTreeStyle.css" rel="stylesheet" />
<table class="post-form">
    <tr>
        <th style="width: 150px;">角色名：</th>
        <td>
            <input id="RoleName" name="RoleName" lay-verify="required" lay-msg="角色名不能为空" class="layui-input" type="text" value="@Model.RoleName">
        </td>
    </tr>
    <tr>
        <th>说明：</th>
        <td>
            <textarea id="Description" name="Description" class="layui-input">@Model.Description</textarea>
        </td>
    </tr>
    <tr>
        <th>权限分配：</th>
        <td>
            <div style="width: 300px; height: 300px; overflow: scroll; border: solid 1px #d4d4d4;">
                <ul id="TreePermission" class="ztree" style="width: 280px; overflow: auto;"></ul>
            </div>
            <input type="hidden" id="PermissionIDs" name="PermissionIDs" value="@ViewBag.PermissionIDs" />
        </td>
    </tr>
    <tr>
        <th></th>
        <td>
            <button id="post_btn" type="submit" class="layui-btn" lay-submit="" lay-filter="post">保 存</button>
            <a href="javascript:void(0)" onclick="parent.CloseWindow();" class="layui-btn layui-btn-normal">返回列表</a>
        </td>
    </tr>
</table>

<script src="/lib/zTree_v3/js/jquery.ztree.all.min.js"></script>
<script>
    layui.use(['form'], function () {
        var form = layui.form;

        //监听提交
        form.on('submit(post)', function (data) {
            console.log(JSON.stringify(data.field));
            return true;
        });
    });
    //ZTree配置
    var setting = {
        check: {
            enable: true
        },
        data: {
            simpleData: {
                enable: true
            }
        },
        callback: {
            onCheck: getAllCheckNodes
        }
    };

    $(function () {
        //ZTree初始化
        var json = '@Html.Raw( ViewBag.PermissionList)';
        if (json == '')
            return;
        setting.check.chkboxType = { "Y": "p", "N": "s" };//被勾选时[关联父]，取消勾选时[关联子]
        $.fn.zTree.init($("#TreePermission"), setting, eval(json));
        var treeObj = $.fn.zTree.getZTreeObj("TreePermission");
        treeObj.expandAll(true);
    });

    //获取所有选中的值
    function getAllCheckNodes() {
        var treeObj = $.fn.zTree.getZTreeObj('TreePermission'),
                nodes = treeObj.getCheckedNodes(true),
                v = '';
        for (var i = 0; i < nodes.length; i++) {
            if (v != '')
                v += ',';
            v += nodes[i].value;
        }
        $('#PermissionIDs').val(v);
    }
</script>

YeZiFang.Admin/Views/System/RoleList.cshtml
@model Pager<GetRoleListResponse>
@{
    ViewBag.Title = "角色列表";
}

<div class="container">
    @using (Html.BeginForm("RoleList", "System", FormMethod.Get, new { @class = "layui-form search-form layui-elem-quote", @id = "searchForm" }))
    {
        <table>
            <tr>
                <th>名称：</th>
                <td>
                    <input id="RoleName" name="RoleName" class="layui-input" type="text" value="">
                </td>
                <td>
                    <input type="submit" class="layui-btn layui-btn-sm" value="查 询" />
                </td>
            </tr>
        </table>
    }
        <div style="padding:0px 10px;">
            <a class="layui-btn layui-btn-sm layui-btn-normal" href="javascript:void(0);" onclick="AddOrEdit()">
                <i class="layui-icon layui-icon-tianjia2"></i>添加角色</a>
        </div>
    <table class="layui-table" id="list">
        <thead>
            <tr>
                <th style="width:45px; text-align:center;">#</th>
                <th>角色ID</th>
                <th>角色名</th>
                <th>备注</th>
                <th>创建人</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @{ int index = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:45px; text-align:center;">@(index++)</td>
                    <td>@item.ID</td>
                    <td>@item.RoleName</td>
                    <td>@item.Description</td>
                    <td>@item.CreateUser</td>
                    <td>@item.CreateTime</td>
                    <td>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" href="javascript:void(0)" onclick="AddOrEdit('@item.ID')"><i class="layui-icon layui-icon-bianji"></i>编辑</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" onclick="javascript:Delete('/System/RoleDelete/@item.ID');"><i class="layui-icon layui-icon-delete"></i>删除</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.Partial("_Pager", Model)
</div>
<script>
    function AddOrEdit(id) {
        if (id == undefined) {
            ShowMaxWindow('===添加角色信息===', '/System/RoleAdd');
        }
        else {
            ShowMaxWindow('===编辑角色信息===', '/System/RoleEdit/' + id);
        }
    }
</script>

YeZiFang.Admin/Views/System/UserAdd.cshtml
@model UserInfo

<body>
    <form id="UserAdd" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="UserAdd"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("UserForm")
    </form>
</body>

YeZiFang.Admin/Views/System/UserEdit.cshtml
@model UserInfo

<body>
    <form id="UserEdit" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="UserEdit"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">
        @await Html.PartialAsync("UserForm")
    </form>
</body>

YeZiFang.Admin/Views/System/UserForm.cshtml
@model UserInfo
<table class="post-form">
    <tr>
        <th style="width: 150px;">用户名：</th>
        <td>
            <input id="UserName" name="UserName" lay-verify="required" lay-msg="用户名不能为空" class="layui-input" type="text" value="@Model.UserName"
                    @(string.IsNullOrEmpty(Model.ID)?"":"disabled=\"disabled\"")>
        </td>
    </tr>
    @if (string.IsNullOrEmpty(Model.ID))
    {
        <tr>
            <th>登录密码：</th>
            <td>
                <input id="Password" name="Password" lay-verify="required" lay-msg="登录密码不能为空" class="layui-input" type="password" value="@Model.Password">
            </td>
        </tr>
        <tr>
            <th>确认密码：</th>
            <td>
                <input id="Password0" name="Password0" lay-verify="confirmPassword" class="layui-input" type="password" value="@Model.Password">
            </td>
        </tr>
    }
    <tr>
        <th>姓名：</th>
        <td>
            <input id="RealName" name="RealName" lay-verify="required" lay-msg="姓名不能为空" class="layui-input" type="text" value="@Model.RealName">
        </td>
    </tr>
    <tr>
        <th>超级管理员：</th>
        <td>
            <input name="IsAdmin" lay-skin="switch" lay-text="是|否" checked="@(Model.IsAdmin?"checked":"")" type="checkbox">
        </td>
    </tr>
        <tr>
            <th>所属角色:</th>
            <td>
                @Html.DropDownList("RoleID", ViewData["Roles"] as SelectList, "-请选择-", new { @class = "layui-input" })
            </td>
        </tr>
    <tr>
        <th></th>
        <td>
            <button id="post_btn" type="submit" class="layui-btn" lay-submit="" lay-filter="post">保 存</button>
            <a href="javascript:void(0)" onclick="parent.CloseWindow();" class="layui-btn layui-btn-normal">返回列表</a>
        </td>
    </tr>
</table>
<script>
    layui.use(['form', 'layer'], function () {
        var form = layui.form,
        layer = layui.layer;
        //自定义验证规则
        form.verify({
            confirmPassword: function (value) {
                if (value != $('#Password').val()) {
                    return '两次输入密码不一致！';
                }
            }
        });
        //监听提交
        form.on('submit(post)', function (data) {
            console.log(JSON.stringify(data.field));
            return true;
        });
    });
</script>

YeZiFang.Admin/Views/System/UserList.cshtml
@model Pager<GetUserListResponse>
@{
    ViewBag.Title = "用户列表";
}

<div class="container">
    @using (Html.BeginForm("UserList", "System", FormMethod.Get, new { @class = "layui-form search-form layui-elem-quote", @id = "searchForm" }))
    {
        <table>
            <tr>
                <th>用户名：</th>
                <td>
                    <input id="UserName" name="UserName" class="layui-input" type="text">
                </td>
                <th>姓名：</th>
                <td>
                    <input id="Name" name="Name" class="layui-input" type="text">
                </td>
                @*<th>起止时间：</th>
                    <td>
                        <div class="layui-inline">
                            <div class="layui-input-inline">
                                <input id="StartTime" name="StartTime" class="layui-input" type="text">
                            </div>-
                            <div class="layui-input-inline">
                                <input id="EndTime" name="EndTime" class="layui-input" type="text">
                            </div>
                        </div>
                    </td>*@
                <td>
                    <input type="submit" class="layui-btn layui-btn-sm" value="查 询" />
                </td>
            </tr>
        </table>
    }
    <div style="padding:0px 10px;">
        <a class="layui-btn layui-btn-sm layui-btn-normal" href="javascript:void(0);" onclick="AddOrEdit()">
            <i class="layui-icon layui-icon-tianjia2"></i>添加用户
        </a>
    </div>
    <table class="layui-table" id="list">
        <thead>
            <tr>
                <th style="text-align:center;">#</th>
                <th>用户ID</th>
                <th>用户名</th>
                <th>姓名</th>
                <th>所属角色</th>
                <th>创建人</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @{ int index = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:20px; text-align:center;">@(index++)</td>
                    <td>@item.ID</td>
                    <td>@item.UserName</td>
                    <td>@item.RealName</td>
                    <td>@(item.IsAdmin ? "超级管理员" : item.RoleName)</td>
                    <td>@item.CreateUser</td>
                    <td>@item.CreateTime</td>
                    <td>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" onclick="AddOrEdit('@item.ID')"><i class="layui-icon layui-icon-bianji"></i>编辑</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" onclick="javascript:Delete('/System/UserDelete/@item.ID');"><i class="layui-icon layui-icon-delete"></i>删除</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @await Html.PartialAsync("_Pager", Model)
</div>
<script>
    function AddOrEdit(id) {
        if (id == undefined) {
            ShowMaxWindow('===添加用户信息===', '/System/UserAdd');
        }
        else {
            ShowMaxWindow('===编辑用户信息===', '/System/UserEdit/' + id);
        }
    }

    //layui.use(['laydate'], function () {
    //    var laydate = layui.laydate
    //    //日期
    //    laydate.render({
    //        elem: '#StartTime'
    //    });
    //    laydate.render({
    //        elem: '#EndTime'
    //    });
    //});
</script>

YeZiFang.Admin/Views/System/UserPwd.cshtml
@model UserInfo

<body>
    <form id="UserAdd" class="layui-form layui-form-pane"
          asp-controller="System" asp-action="UserPwd"
          data-ajax="true"
          data-ajax-mode="replace"
          data-ajax-update="#"
          data-ajax-method="Post"
          data-ajax-success="Callback">


        <table class="post-form">
            <tr>
                <th style="width: 80px;">用户名：</th>
                <td>
                    @Html.Label("UserName", Model.UserName)
                </td>
            </tr>
            <tr>
                <th>登录密码：</th>
                <td>
                    <input id="Password" name="Password" lay-verify="required" lay-msg="请输入登录密码" class="layui-input" type="text" value="">
                </td>
            </tr>
            <tr>
                <th>确认密码：</th>
                <td>
                    <input id="Password0" name="Password0" lay-verify="confirmPassword" class="layui-input" type="text" value="">
                </td>
            </tr>
            <tr>
                <th></th>
                <td>
                    <button type="submit" class="layui-btn" lay-submit="" lay-filter="post">保 存</button>
                    <a href="javascript:void(0)" onclick="parent.CloseWindow();" class="layui-btn layui-btn-normal">取消</a>
                </td>
            </tr>
        </table>
    </form>
    <script>
        layui.use(['form'], function () {
            var form = layui.form
            //自定义验证规则
            form.verify({
                confirmPassword: function (value) {
                    if (value != $('#Password').val()) {
                        return '两次输入密码不一致！';
                    }
                }
            });
        });
    </script>
</body>